export const APPOINTMENT_LIST_REQUEST = "APPOINTMENT_LIST_REQUEST";
export const APPOINTMENT_LIST_SUCCESS = "APPOINTMENT_LIST_SUCCESS";
export const APPOINTMENT_LIST_FAIL = "APPOINTMENT_LIST_FAIL";

export const APPOINTMENT_ADD_REQUEST = "APPOINTMENT_ADD_REQUEST";
export const APPOINTMENT_ADD_SUCCESS = "APPOINTMENT_ADD_SUCCESS";
export const APPOINTMENT_ADD_FAIL = "APPOINTMENT_ADD_FAIL";

export const APPOINTMENT_DELETE_REQUEST = "APPOINTMENT_DELETE_REQUEST";
export const APPOINTMENT_DELETE_SUCCESS = "APPOINTMENT_DELETE_SUCCESS";
export const APPOINTMENT_DELETE_FAIL = "APPOINTMENT_DELETE_FAIL";
