export const BRANCH_LIST_REQUEST = "BRANCH_LIST_REQUEST";
export const BRANCH_LIST_SUCCESS = "BRANCH_LIST_SUCCESS";
export const BRANCH_LIST_FAIL = "BRANCH_LIST_FAIL";

export const BRANCH_ADD_REQUEST = "BRANCH_ADD_REQUEST";
export const BRANCH_ADD_SUCCESS = "BRANCH_ADD_SUCCESS";
export const BRANCH_ADD_FAIL = "BRANCH_ADD_FAIL";

export const BRANCH_DELETE_REQUEST = "BRANCH_DELETE_REQUEST";
export const BRANCH_DELETE_SUCCESS = "BRANCH_DELETE_SUCCESS";
export const BRANCH_DELETE_FAIL = "BRANCH_DELETE_FAIL";
