export const PATIENT_LIST_REQUEST = "PATIENT_LIST_REQUEST";
export const PATIENT_LIST_SUCCESS = "PATIENT_LIST_SUCCESS";
export const PATIENT_LIST_FAIL = "PATIENT_LIST_FAIL";

export const PATIENT_ADD_REQUEST = "PATIENT_ADD_REQUEST";
export const PATIENT_ADD_SUCCESS = "PATIENT_ADD_SUCCESS";
export const PATIENT_ADD_FAIL = "PATIENT_ADD_FAIL";

export const PATIENT_DELETE_REQUEST = "PATIENT_DELETE_REQUEST";
export const PATIENT_DELETE_SUCCESS = "PATIENT_DELETE_SUCCESS";
export const PATIENT_DELETE_FAIL = "PATIENT_DELETE_FAIL";
