export const WARD_LIST_REQUEST = "WARD_LIST_REQUEST";
export const WARD_LIST_SUCCESS = "WARD_LIST_SUCCESS";
export const WARD_LIST_FAIL = "WARD_LIST_FAIL";

export const WARD_ADD_REQUEST = "WARD_ADD_REQUEST";
export const WARD_ADD_SUCCESS = "WARD_ADD_SUCCESS";
export const WARD_ADD_FAIL = "WARD_ADD_FAIL";

export const WARD_DELETE_REQUEST = "WARD_DELETE_REQUEST";
export const WARD_DELETE_SUCCESS = "WARD_DELETE_SUCCESS";
export const WARD_DELETE_FAIL = "WARD_DELETE_FAIL";
